# Generated by Django 5.2.16 on 2026-07-15 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='error', max_length=16)),
                ('message', models.TextField()),
                ('stacktrace', models.TextField(blank=True, default='')),
                ('platform', models.CharField(blank=True, default='', max_length=32)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('device_model', models.CharField(blank=True, default='', max_length=128)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('client_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='api_errorlo_level_6d5748_idx')],
            },
        ),
    ]
